### PR TITLE
Add Basic .npy Control

### PR DESCRIPTION
**Pull request by zalo**
@kevinzakka Not sure what the .npy's framerate is xD

### CODE REVIEW

**Comment by kevinzakka** [comment]
Let me push the npy to the repo. I believe the control frequency is 0.05 in my robopianist repo!

**Comment by zalo** [comment]
Yeah, I added the twinkle twinkle one to this PR 🙃

**Comment by kevinzakka** [comment]
Nice, you are one step ahead haha :) !

**Comment by zalo** [comment]
You'll probably want to do something more like:
```javascript
            currentCtrl[i] = this.pianoControl.data[
              (currentCtrl.length * (Math.floor(this.mujoco_time / 50)) % this.pianoControl.shape[0]) + i];
```

to loop the performance, but I imagine you'll need to reset the state of the sim with each run-through too.

**Comment by kevinzakka** [comment]
I have a canonicalized action space in robopianist (rescale actions to -1, 1) so let me regenerated the actions unscale and push them to the repo first!

**Comment by kevinzakka** [comment]
In numpy, this is a 2D array of shape (158, 29).

**Comment by kevinzakka** [comment]
Oh just remembered, I have a sustain pedal in my environment :p. So we need to ignore the last index of every action!

**Pull request merged**
